import TmpPoster from '/public/assets/tmp-poster.jpg';

export enum GuSeq {
  KANGBUK = 1,
  KANGNAM,
  KANGDONG,
  KANGSEO,
  KWANAK,
  KWANGJIN,
  KURO,
  KUMCHON,
  NOWON,
  TOBONG,
  DONGDAEMUN,
  DONGJAK,
  MAPO,
  SEODAMUN,
  SEOCHO,
  SUNGDONG,
  SUNGBUK,
  SONGPA,
  YANGCHON,
  YOUNGDUNGPO,
  YONGSAN,
  UNPYONG,
  JONGNO,
  JUNG,
  JUNGRANG,
}

export enum GuName {
  KANGBUK = '강북구',
  KANGNAM = '강남구',
  KANGDONG = '강동구',
  KANGSEO = '강서구',
  KWANAK = '관악구',
  KWANGJIN = '광진구',
  KURO = '구로구',
  KUMCHON = '금천구',
  NOWON = '노원구',
  TOBONG = '도봉구',
  DONGDAEMUN = '동대문구',
  DONGJAK = '동작구',
  MAPO = '마포구',
  SEODAMUN = '서대문구',
  SEOCHO = '서초구',
  SUNGDONG = '성동구',
  SUNGBUK = '성북구',
  SONGPA = '송파구',
  YANGCHON = '양천구',
  YOUNGDUNGPO = '영등포구',
  YONGSAN = '용산구',
  UNPYONG = '은평구',
  JONGNO = '종로구',
  JUNG = '중구',
  JUNGRANG = '중랑구',
}

export const ALERTMODAL_CONTENT = [
  {
    title: '라보엠',
    src: TmpPoster,
    schedule: '행사 전날',
  },
  {
    title: '오페라 갈라',
    src: TmpPoster,
    schedule: '행사 당일',
  },
  {
    title: '한여름의 메시아',
    src: TmpPoster,
    schedule: '행사 하루 전',
  },
];
